AllCops:
  TargetRubyVersion: 3.3.1

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# For rspec line limit
Metrics/BlockLength:
  AllowedMethods: ["describe"]
  Exclude: 
  - 'bin/app.rb'